export type AppScreen =
  | 'connect'
  | 'role'
  | 'solar-system'
  | 'mission-complete'
  | 'mission-control';

// ─── Node Status & Scoring ────────────────────────────────────────────────────

export type NodeStatus = 'untouched' | 'reading' | 'complete';

export type NodeColour = 'green' | 'yellow' | 'red';

export type ReadinessLevel =
  | 'Not Started'
  | 'In Progress'
  | 'Partially Ready'
  | 'Ready'
  | 'Fully Prepared';

// ─── MCP ──────────────────────────────────────────────────────────────────────

export interface MCPConnection {
  url: string;
  token: string;
  status: 'idle' | 'connecting' | 'connected' | 'failed';
  documentCount: number;
  sources: MCPSource[];
}

export interface MCPSource {
  name: string;
  count: number;
}

export interface MCPDocument {
  id: string;
  source: string;
  title: string;
  content: string;
  metadata: Record<string, string>;
}

// ─── User Profile ─────────────────────────────────────────────────────────────

export interface UserProfile {
  roleDescription: string;
  parsedRole: string;
  parsedFocus: string[];
  experience: string;
  experienceLevel?: string;
}

// ─── Onboarding Briefing Card ─────────────────────────────────────────────────
// Generated by the Architect alongside the nodes. Displayed as the left-side
// collapsible panel from the moment the map is shown.

export interface OnboardingBriefingCard {
  projectName: string;
  projectIntro: string;         // 2-3 sentence plain-English project overview
  roleIntro: string;            // 1-2 sentences: what this person specifically does
  yourResponsibilities: string[]; // 3-5 bullet points specific to this role
  keyContacts: OnboardingContact[];
  firstWeekTips: string[];      // 3-5 concrete actions for day 1-5
  suggestedPath: string[];      // ordered list of node titles in recommended read order
  doNotBreak: string[];         // 2-4 critical things not to touch without understanding
}

export interface OnboardingContact {
  name: string;
  role: string;
  contact: string;              // email / Slack / "ask in #channel"
  why: string;                  // one sentence: why this person matters for this role
}

// ─── Knowledge Node ───────────────────────────────────────────────────────────

export interface KnowledgeNode {
  id: string;
  title: string;
  summary: string;
  keyTakeaways: string[];
  roleRelevance: string;
  diagrams: Diagram[];
  keyContacts: NodeKeyContact[];
  links: ResourceLink[];
  sources: SourceReference[];
  quiz: Quiz;
  status: NodeStatus;
  score: QuizScore | null;
  // Visual layout fields (used for 3D map positioning)
  order: number;
  visualConfig: NodeVisualConfig;
}

export interface NodeVisualConfig {
  size: number;
  color: string;
  emissiveColor: string;
  orbitRadius: number;
  orbitSpeed: number;
}

export interface Diagram {
  title: string;
  content: string;
  caption: string;
}

export interface NodeKeyContact {
  name: string;
  role: string;
  relevance: string;
}

export interface ResourceLink {
  label: string;
  url: string;
  type: 'document' | 'ticket' | 'repo' | 'confluence' | 'other';
}

export interface SourceReference {
  documentTitle: string;
  source: string;
  excerpt: string;
}

// ─── Quiz ─────────────────────────────────────────────────────────────────────

export interface Quiz {
  questions: QuizQuestion[];
}

export interface QuizQuestion {
  id: string;
  question: string;
  type: 'multiple_choice' | 'true_false';
  options: QuizOption[];
  correctOptionId: string;
  explanation: string;
}

export interface QuizOption {
  id: string;
  text: string;
}

export interface QuizScore {
  totalQuestions: number;
  correctAnswers: number;
  percentage: number;
  nodeColour: NodeColour;
  completedAt: string;
}

// ─── Overall Score ────────────────────────────────────────────────────────────

export interface OverallScore {
  totalNodes: number;
  completedNodes: number;
  greenNodes: number;
  yellowNodes: number;
  redNodes: number;
  averagePercentage: number;
  readinessLevel: ReadinessLevel;
}

// ─── Chat ─────────────────────────────────────────────────────────────────────

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  referencedDocuments?: string[];
}

// ─── Legacy: Planet types kept for backward compat with visual map ─────────────
// The KnowledgeNode is the primary type. Planet is an alias for the 3D renderer.

export type Planet = KnowledgeNode;

export type PlanetStatus = NodeStatus | 'locked' | 'available' | 'active' | 'completed';

export type AstronautRank = ReadinessLevel;

// ─── Briefing Card ────────────────────────────────────────────────────────────

export interface MissionBriefingCard {
  projectSnapshot: string;
  roleAndOwnership: string;
  topPriorities: string[];
  topRisks: string[];
  keyContacts: KeyContact[];
  thingsNotToBreak: string[];
  firstWeekFocus: string;
}

export interface KeyContact {
  name: string;
  role: string;
  owns: string;
}

// ─── Store State ──────────────────────────────────────────────────────────────

export interface OrbitState {
  mcpConnection: MCPConnection;
  mcpDocuments: MCPDocument[];
  userProfile: UserProfile | null;
  nodes: KnowledgeNode[];
  selectedNodeId: string | null;
  overallScore: OverallScore;
  onboardingBriefingCard: OnboardingBriefingCard | null;
  missionBriefingCard: MissionBriefingCard | null;
  chatMessages: ChatMessage[];
  isChatOpen: boolean;
  currentScreen: AppScreen;
  isLoading: boolean;
  loadingMessage: string;
  // Legacy compat
  planets: KnowledgeNode[];
  activePlanetId: string | null;
  activePlanetPhase: 'transmission' | 'mission' | 'debrief' | null;
  totalXP: number;
  astronautRank: AstronautRank | null;
}

// ─── Legacy challenge types (kept for backward compat) ────────────────────────

export type ChallengeType = 'SCENARIO' | 'ROLEPLAY' | 'DETECTIVE' | 'BUILD' | 'TRANSMISSION_DECODE';

export interface Challenge {
  type: ChallengeType;
  title: string;
  setup: string;
  prompt: string;
  options?: ChallengeOption[];
  clues?: string[];
  codeSnippets?: CodeSnippet[];
  artefact?: string;
  userResponse: string;
}

export interface ChallengeOption {
  id: string;
  label: string;
  text: string;
}

export interface CodeSnippet {
  id: string;
  label: string;
  language: string;
  code: string;
}

export interface Debrief {
  strengths: string;
  gaps: string;
  deeperContext: string;
  xpAwarded: number;
  personalisation: string;
}

export interface PlanetVisualConfig {
  size: number;
  color: string;
  secondaryColor: string;
  emissiveColor: string;
  orbitRadius: number;
  orbitSpeed: number;
  hasRings: boolean;
  ringSeed: number;
  atmosphereColor: string;
  textureType: 'rocky' | 'gas' | 'icy' | 'lava' | 'ocean' | 'storm';
}
